In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("test.csv")
df_t = pd.read_csv("test_num.csv")

In [3]:
df

        Source Target
0           이유    피의자
1           이유    피의자
2           이유    피의자
3           이유    피의자
4           이유    피의자
5           이유    피의자
6           이유    피의자
7           이유    피의자
8           이유    피의자
9           이유    우울증
10          이유    우울증
11          이유    우울증
12          이유    우울증
13          이유    우울증
14          이유    우울증
15          이유    우울증
16          이유    우울증
17          이유    우울증
18          이유     뉴스
19          이유     뉴스
20          이유     뉴스
21          이유     뉴스
22          이유     뉴스
23          이유     뉴스
24          이유     뉴스
25          이유     뉴스
26          이유     뉴스
27          이유     심신
28          이유     심신
29          이유     심신
...        ...    ...
3878300     치료     감형
3878301     치료     감형
3878302     치료     감형
3878303     치료     감형
3878304     치료     감형
3878305     치료     감형
3878306     치료     감형
3878307     치료     감형
3878308     치료     감형
3878309     치료     감형
3878310     치료     감형
3878311     치료     감형
3878312     치료     감형
3878313     치료     감형
3878314     치료      술
3878315     치료      술
3878316     치료      술
3878317     치료      술
3878318     치료      술
3878319     치료      술
3878320     치료      술
3878321     치료      술
3878322     치료      술
3878323     치료      술
3878324     치료      술
3878325     치료      술
3878326     치료      술
3878327     치료      술
3878328     치료      술
3878329     치료      술

[3878330 rows x 2 columns]

In [4]:
df_t

                   Pair   Num
0          ('심신', '미약')  5274
1          ('미약', '심신')  5274
2          ('심신', '사건')  3783
3          ('사건', '심신')  3783
4           ('관', '비서')  3437
5           ('비서', '관')  3437
6          ('미약', '사건')  3279
7          ('사건', '미약')  3279
8          ('청원', '국민')  2448
9          ('국민', '청원')  2448
10         ('심신', '경우')  2430
11         ('경우', '심신')  2430
12          ('사건', '관')  2286
13          ('관', '사건')  2286
14          ('관', '정혜')  2270
15           ('관', '승')  2270
16          ('정혜', '관')  2270
17           ('승', '관')  2270
18         ('비서', '정혜')  2143
19          ('비서', '승')  2143
20         ('정혜', '비서')  2143
21          ('승', '비서')  2143
22         ('미약', '경우')  2106
23         ('경우', '미약')  2106
24         ('난민', '신청')  2060
25         ('신청', '난민')  2060
26         ('사건', '경우')  2041
27         ('경우', '사건')  2041
28         ('사건', '비서')  2033
29         ('비서', '사건')  2033
...                 ...   ...
89400      ('첨부', '요청')     1
89401     ('링크', '청와대')     1
89402      ('링크', '질의')     1
89403      ('링크', '접수')     1
89404     ('링크', '김기식')     1
89405  ('링크', '금융감독원장')     1
89406       ('링크', '외')     1
89407      ('링크', '유성')     1
89408      ('링크', '해외')     1
89409      ('링크', '출장')     1
89410       ('링크', '총')     1
89411      ('링크', '논란')     1
89412       ('링크', '적')     1
89413      ('링크', '법성')     1
89414      ('링크', '여부')     1
89415      ('링크', '금일')     1
89416      ('링크', '해당')     1
89417      ('링크', '대해')     1
89418      ('링크', '국민')     1
89419      ('링크', '행위')     1
89420      ('링크', '확인')     1
89421      ('링크', '현직')     1
89422      ('링크', '전체')     1
89423     ('링크', '위법성')     1
89424      ('링크', '전원')     1
89425      ('링크', '처벌')     1
89426      ('링크', '사용')     1
89427      ('링크', '세금')     1
89428      ('링크', '환수')     1
89429      ('링크', '요청')     1

[89430 rows x 2 columns]

In [5]:
df1 = df[df["Source"]=="심신"]
df1

        Source Target
900         심신     이유
901         심신     이유
902         심신     이유
903         심신     이유
904         심신     이유
905         심신     이유
906         심신     이유
907         심신     이유
908         심신     이유
909         심신    피의자
910         심신    피의자
911         심신    피의자
912         심신    피의자
913         심신    피의자
914         심신    피의자
915         심신    피의자
916         심신    피의자
917         심신    피의자
918         심신    우울증
919         심신    우울증
920         심신    우울증
921         심신    우울증
922         심신    우울증
923         심신    우울증
924         심신    우울증
925         심신    우울증
926         심신    우울증
927         심신     뉴스
928         심신     뉴스
929         심신     뉴스
...        ...    ...
3653247     심신     치료
3653248     심신     치료
3653249     심신     치료
3653250     심신     치료
3653251     심신     치료
3653252     심신     치료
3653253     심신     치료
3653254     심신     치료
3653255     심신     치료
3653256     심신     치료
3653257     심신     치료
3653258     심신     치료
3653259     심신     치료
3653260     심신     치료
3653261     심신     치료
3653262     심신     치료
3653263     심신     치료
3653264     심신     치료
3653265     심신     치료
3653266     심신     치료
3653267     심신     치료
3653268     심신     치료
3653269     심신     치료
3653270     심신     치료
3653271     심신     치료
3653272     심신     치료
3653273     심신     치료
3653274     심신     치료
3653275     심신     치료
3653276     심신     치료

[62190 rows x 2 columns]

In [6]:
df2 = df[df["Source"]=="의혹"]
df2

Empty DataFrame
Columns: [Source, Target]
Index: []

In [10]:
t = df[df["Source"]=="의혹"]

In [11]:
t1 = df[df["Source"]=="매크로"]

In [12]:
t2 = df[df["Source"]=="여론조작"]

In [14]:
t = t.append(t2)

In [18]:
t1.to_csv("test1.csv",index=False)

In [6]:
df_t["Pair"][0], df_t["Pair"][0].find('심신')

("('심신', '미약')", 2)

In [7]:
df_t

                   Pair   Num
0          ('심신', '미약')  5274
1          ('미약', '심신')  5274
2          ('심신', '사건')  3783
3          ('사건', '심신')  3783
4           ('관', '비서')  3437
5           ('비서', '관')  3437
6          ('미약', '사건')  3279
7          ('사건', '미약')  3279
8          ('청원', '국민')  2448
9          ('국민', '청원')  2448
10         ('심신', '경우')  2430
11         ('경우', '심신')  2430
12          ('사건', '관')  2286
13          ('관', '사건')  2286
14          ('관', '정혜')  2270
15           ('관', '승')  2270
16          ('정혜', '관')  2270
17           ('승', '관')  2270
18         ('비서', '정혜')  2143
19          ('비서', '승')  2143
20         ('정혜', '비서')  2143
21          ('승', '비서')  2143
22         ('미약', '경우')  2106
23         ('경우', '미약')  2106
24         ('난민', '신청')  2060
25         ('신청', '난민')  2060
26         ('사건', '경우')  2041
27         ('경우', '사건')  2041
28         ('사건', '비서')  2033
29         ('비서', '사건')  2033
...                 ...   ...
89400      ('첨부', '요청')     1
89401     ('링크', '청와대')     1
89402      ('링크', '질의')     1
89403      ('링크', '접수')     1
89404     ('링크', '김기식')     1
89405  ('링크', '금융감독원장')     1
89406       ('링크', '외')     1
89407      ('링크', '유성')     1
89408      ('링크', '해외')     1
89409      ('링크', '출장')     1
89410       ('링크', '총')     1
89411      ('링크', '논란')     1
89412       ('링크', '적')     1
89413      ('링크', '법성')     1
89414      ('링크', '여부')     1
89415      ('링크', '금일')     1
89416      ('링크', '해당')     1
89417      ('링크', '대해')     1
89418      ('링크', '국민')     1
89419      ('링크', '행위')     1
89420      ('링크', '확인')     1
89421      ('링크', '현직')     1
89422      ('링크', '전체')     1
89423     ('링크', '위법성')     1
89424      ('링크', '전원')     1
89425      ('링크', '처벌')     1
89426      ('링크', '사용')     1
89427      ('링크', '세금')     1
89428      ('링크', '환수')     1
89429      ('링크', '요청')     1

[89430 rows x 2 columns]

In [8]:
def fine_word(dft, word):
    idx = dft.find(word)
    if(idx<0):
        return False
    else:
        return True

In [22]:
def find_dfs(df_t, word, num, go=0):
    hangul = re.compile('[^ㄱ-ㅣ가-힣]+')
    results = []
    test = df_t[df_t['Pair'].apply(lambda x: fine_word(x,word))]
    for i,t in test[:num*2].iterrows():
        f_word = t['Pair'][t['Pair'].find(word)+len(word):]
        result = hangul.sub('', f_word)
        if(result):
            if(go):
                print(result, t["Num"])
            results.append(result)
            
    return results

In [48]:
def fine_list(dft, lists):
    return dft in lists

In [73]:
def make_relation(df_t, word, num,data_num):
    hangul = re.compile('[^ㄱ-ㅣ가-힣]+')
    words = []
    words = find_dfs(df_t, word, num,go=1)
    words.append(word)
    print(words)
    t = df[df["Source"]==words[0]]
    for word in words:
        t_df = df[df["Source"]==word]
        top_list = find_dfs(df_t, word, data_num)
        t = t.append(t_df[t_df['Target'].apply(lambda x: fine_list(x,top_list))])
        print(top_list)
    return t

In [74]:
word = "뉴미디어"
node_num = 5
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

관 1579
비서 1489
국민 1014
난민 1008
['관', '비서', '국민', '난민', '뉴미디어']
['비서', '사건', '정혜', '승', '심신', '청원', '국민', '미약', '뉴미디어', '경우', '미세먼지', '난민', '범죄', '처벌', '대해', '답변', '디지털', '명', '난민', '센터', '지원', '소통', '불법', '여성', '법무', '피해자', '김형', '연', '진행', '련', '련청원']
['관', '정혜', '승', '사건', '심신', '청원', '미약', '국민', '뉴미디어', '경우', '미세먼지', '난민', '디지털', '대해', '답변', '센터', '소통', '처벌', '범죄', '명', '법무', '불법', '여성', '지원', '김형', '연', '진행', '촬영', '이번', '판단']
['청원', '관', '비서', '사건', '난민', '정혜', '승', '답변', '뉴미디어', '대해', '처벌', '경우', '심신', '명', '정부', '범죄', '음주운전', '피해자', '미약', '문제', '이번', '관련', '수사', '불법', '오늘', '장관', '경찰', '촬영', '미세먼지', '진행']
['신청', '심사', '국민', '관', '법무부', '제도', '사회', '정혜', '승', '뉴미디어', '비서', '무사', '증', '박상기', '장관', '협약', '문제', '법', '국가', '제주', '절차', '인정', '보호', '제주도', '대해', '청원', '명', '방안', '정부', '우리나라']
['관', '비서', '국민', '난민', '정혜', '승', '청원', '불법', '사건', '촬영', '미세먼지', '경찰', '여성', '명', '장관', '답변', '관련', '지원', '수사', '대해', '진행', '문제', '대응', '피해', '정부', '범죄', '국가', '처벌', '택배', '지난']

In [75]:
word = "음주운전"
node_num = 3
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

처벌 1060
청원 864
국민 724
['처벌', '청원', '국민', '음주운전']
['청원', '사건', '범죄', '피해자', '경우', '관', '음주운전', '국민', '비서', '심신', '불법', '미약', '정혜', '승', '답변', '촬영', '대해', '형사', '디지털', '명', '여성', '관련', '센터', '청소년', '소통', '강화', '기준', '장관', '법무', '영상']
['국민', '사건', '관', '비서', '처벌', '피해자', '답변', '대해', '경우', '범죄', '정혜', '승', '심신', '미약', '명', '뉴미디어', '음주운전', '이번', '수사', '불법', '관련', '또', '오늘', '지원', '형사', '촬영', '법', '경찰', '센터', '디지털']
['청원', '관', '비서', '사건', '난민', '정혜', '승', '답변', '뉴미디어', '대해', '처벌', '경우', '심신', '명', '정부', '범죄', '음주운전', '피해자', '미약', '문제', '이번', '관련', '수사', '불법', '오늘', '장관', '경찰', '촬영', '미세먼지', '진행']
['처벌', '청원', '국민', '사고', '강화', '경우', '기준', '사망', '행위', '피해자', '대해', '장관', '양형', '살인', '범죄', '대통령', '초범', '교통사고', '수사', '상습', '법', '또', '생각', '공감', '서도', '재범', '구형', '사회', '앞', '답변', '법무부']

In [77]:
word = "피해자"
node_num = 5
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

청원 1570
가해자 1429
처벌 1224
범죄 994
사건 994
['청원', '가해자', '처벌', '범죄', '사건', '피해자']
['국민', '사건', '관', '비서', '처벌', '피해자', '답변', '대해', '경우', '범죄', '정혜', '승', '심신', '미약', '명', '뉴미디어', '음주운전', '이번', '수사', '불법', '관련', '또', '오늘', '지원', '형사', '촬영', '법', '경찰', '센터', '디지털']
['피해자', '명', '청원', '사건', '동생', '관', '형사', '처벌', '모텔', '비서', '범죄', '세', '직장', '보호', '친구', '답변', '국민', '관련', '판결', '대해', '출혈', '경찰', '문', '사회', '소통', '김형', '연', '법무', '폭행', '청소년']
['청원', '사건', '범죄', '피해자', '경우', '관', '음주운전', '국민', '비서', '심신', '불법', '미약', '정혜', '승', '답변', '촬영', '대해', '형사', '디지털', '명', '여성', '관련', '센터', '청소년', '소통', '강화', '기준', '장관', '법무', '영상']
['사건', '처벌', '청원', '관', '심신', '경우', '피해자', '미약', '비서', '형사', '국민', '정혜', '승', '불법', '청소년', '명', '촬영', '대해', '답변', '여성', '디지털', '관련', '지원', '센터', '세', '소통', '법무', '장관', '김형', '연']
['심신', '미약', '관', '경우', '비서', '청원', '정혜', '승', '대해', '범죄', '디지털', '국민', '센터', '처벌', '판단', '소통', '법무', '감경', '김형', '연', '답변', '피해자', '인정', '경찰', '형사', '선고', '불법', '명', '네', '실제']
['청원', '가해자', '처벌', '범죄', '사건', '관', '답변', '명', '경우', '국민', '대해', '보호', '비서', '성폭력', '또', '불법', '형사', '세', '촬영', '조두순', '문', '관련', '조국', '수석', '정혜', '승', '판결', '민정', '여성', '청소년']

In [78]:
word = "조두순"
node_num = 5
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

나영이 684
청원 528
조국 462
수석 462
피해자 462
['나영이', '청원', '조국', '수석', '피해자', '조두순']
['조두순', '글', '사건', '사람', '항문', '나영', '소', '주장', '왜', '술', '생각', '여러분', '페이스북', '교회', '자신', '얼굴', '시작', '변기', '장기', '반대', '아이', '감옥', '이유', '음주', '정말', '대해', '다시', '요즘', '하나', '살', '답', '고', '말']
['국민', '사건', '관', '비서', '처벌', '피해자', '답변', '대해', '경우', '범죄', '정혜', '승', '심신', '미약', '명', '뉴미디어', '음주운전', '이번', '수사', '불법', '관련', '또', '오늘', '지원', '형사', '촬영', '법', '경찰', '센터', '디지털']
['수석', '청원', '조두순', '또', '피해자', '민정', '고민정', '부대', '변인', '대해', '답변', '경우', '청와대', '기준', '범죄', '말씀', '분', '지금', '처벌', '법', '성폭력', '아동', '양형', '때문', '술', '오늘', '여러분', '법인세', '이후', '상태', '현행법', '국민', '생각']
['청원', '조국', '또', '조두순', '피해자', '민정', '대해', '고민정', '부대', '변인', '범죄', '청와대', '기준', '말씀', '답변', '경우', '국민', '생각', '때문', '문제', '분', '지금', '처벌', '오늘', '법', '성폭력', '아동', '양형', '저희', '사람']
['청원', '가해자', '처벌', '범죄', '사건', '관', '답변', '명', '경우', '국민', '대해', '보호', '비서', '성폭력', '또', '불법', '형사', '세', '촬영', '조두순', '문', '관련', '조국', '수석', '정혜', '승', '판결', '민정', '여성', '청소년']
['나영이', '청원', '조국', '수석', '피해자', '민정', '또', '대해', '사건', '고민정', '부대', '변인', '사람', '술', '여러분', '글', '답변', '경우', '생각', '분', '지금', '처벌', '여기', '청와대', '말씀', '기준', '법', '성폭력', '아동', '양형']

In [72]:
word = "뉴미디어"
node_num = 5
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

관 1579
비서 1489
국민 1014
난민 1008
['관', '비서', '국민', '난민', '뉴미디어']
['비서', '사건', '정혜', '승', '심신', '청원', '국민', '미약', '뉴미디어', '경우', '미세먼지', '난민', '범죄', '처벌', '대해', '답변', '디지털', '명', '난민', '센터', '지원', '소통', '불법', '여성', '법무', '피해자', '김형', '연', '진행', '련', '련청원']
['관', '정혜', '승', '사건', '심신', '청원', '미약', '국민', '뉴미디어', '경우', '미세먼지', '난민', '디지털', '대해', '답변', '센터', '소통', '처벌', '범죄', '명', '법무', '불법', '여성', '지원', '김형', '연', '진행', '촬영', '이번', '판단']
['청원', '관', '비서', '사건', '난민', '정혜', '승', '답변', '뉴미디어', '대해', '처벌', '경우', '심신', '명', '정부', '범죄', '음주운전', '피해자', '미약', '문제', '이번', '관련', '수사', '불법', '오늘', '장관', '경찰', '촬영', '미세먼지', '진행']
['신청', '심사', '국민', '관', '법무부', '제도', '사회', '정혜', '승', '뉴미디어', '비서', '무사', '증', '박상기', '장관', '협약', '문제', '법', '국가', '제주', '절차', '인정', '보호', '제주도', '대해', '청원', '명', '방안', '정부', '우리나라']
['관', '비서', '국민', '난민', '정혜', '승', '청원', '불법', '사건', '촬영', '미세먼지', '경찰', '여성', '명', '장관', '답변', '관련', '지원', '수사', '대해', '진행', '문제', '대응', '피해', '정부', '범죄', '국가', '처벌', '택배', '지난']

In [79]:
word = "난민"
node_num = 5
data_num = 30
#30개만 나오게 개당
make_relation(df_t, word , node_num, data_num).to_csv(word + str(node_num)+".csv",index=False)

신청 2060
심사 1644
국민 1208
관 1176
법무부 1176
['신청', '심사', '국민', '관', '법무부', '난민']
['난민', '심사', '국민', '관', '법무부', '문제', '사회', '제도', '정혜', '승', '뉴미디어', '비서', '무사', '증', '박상기', '장관', '협약', '보호', '법', '국가', '제주도', '제주', '절차', '인정', '대해', '청원', '명', '방안', '정부', '우리나라']
['난민', '신청', '국민', '관', '법무부', '제도', '정혜', '승', '뉴미디어', '비서', '사회', '무사', '증', '박상기', '장관', '협약', '문제', '법', '국가', '제주', '절차', '인정', '보호', '제주도', '청원', '명', '방안', '정부', '우리나라', '대해']
['청원', '관', '비서', '사건', '난민', '정혜', '승', '답변', '뉴미디어', '대해', '처벌', '경우', '심신', '명', '정부', '범죄', '음주운전', '피해자', '미약', '문제', '이번', '관련', '수사', '불법', '오늘', '장관', '경찰', '촬영', '미세먼지', '진행']
['비서', '사건', '정혜', '승', '심신', '청원', '국민', '미약', '뉴미디어', '경우', '미세먼지', '난민', '범죄', '처벌', '대해', '답변', '디지털', '명', '난민', '센터', '지원', '소통', '불법', '여성', '법무', '피해자', '김형', '연', '진행', '련', '련청원']
['난민', '신청', '국민', '청원', '심사', '처벌', '관', '법', '장관', '범죄', '사회', '명', '음주운전', '정혜', '승', '뉴미디어', '비서', '제도', '대해', '경우', '관련', '무사', '증', '박상기', '협약', '정부', '청소년', '지원', '국가', '제주', '절차']
['신청', '심사', '국민', '관', '법무부', '제도', '사회', '정혜', '승', '뉴미디어', '비서', '무사', '증', '박상기', '장관', '협약', '문제', '법', '국가', '제주', '절차', '인정', '보호', '제주도', '대해', '청원', '명', '방안', '정부', '우리나라']